### ISSUE TITLE
스탑워치 html 설계

### ISSUE THREAD

**Issue by eunoo1995** [nalsae/Stop-watch#2]
#Abstract

스탑워치 html 설계

##tasks
- [x] html 기본 요소 작성
- [x] head 작성
- [x] body 설계

**Comment by nalsae** [comment]
오타가 많긴 하지만.. 알겠습니다.... 파이팅...

**Comment by eunoo1995** [comment]
아니 체크박스 왜안생겨요

**Comment by nalsae** [comment]
오타 신경쓰지 말고 얼른 작업하세요

**Comment by nalsae** [comment]
은우님이 html 만들어야 제가 css 작업하잖아요

**Comment by eunoo1995** [comment]
클론도 안했네 하

**Comment by nalsae** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
